version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
    permissions:
      - object: /home/ec2-user
        pattern: "**"
        owner: ec2-user
        group: ec2-user
        mode: 755
        type:
          - file
hooks:
  BeforeInstall:
    - location: ./scripts/before-install.sh
      timeout: 900
  AfterInstall:
    - location: ./scripts/after-install.sh
      timeout: 900
    - location: fix-previleges.sh
      timeout: 300
  ApplicationStart:
    - location: ./scripts/application-start.sh
      timeout: 900
  ValidateService:
    - location: ./scripts/validate-service.sh
      timeout: 900
