version: 0.0
os: linux
files:
  - source: appspec.ym
    destination: /home/ec2-user
hooks:
  BeforeInstall:
    - location: ./scripts/before-install.sh
      timeout: 900
      runas: root
  AfterInstall:
    - location: ./scripts/after-install.sh
      timeout: 900
    - location: fix-previleges.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: ./scripts/application-start.sh
      timeout: 900
      runas: root
  ValidateService:
    - location: ./scripts/validate-service.sh
      timeout: 900
      runas: root
